import type { Collaboration } from "@/types/domain";

export const collaborationsByCreator: Record<string, Collaboration[]> = {
  alexis: [
    {
      id: "collab-1",
      campaignId: "campaign-ferngrove-outbound",
      campaignTitle: "Outbound playbook launch",
      creatorProfileId: "creator-alexis",
      brandProfileId: "brand-ferngrove",
      brandName: "Ferngrove",
      brandLogoUrl: "/images/logos/ferngrove.svg",
      status: "active",
      agreedPrice: 620,
      netPayoutToCreator: 465,
      nextActionText: "Publish by Sept 18",
      dueDate: "2026-09-18T00:00:00.000Z",
      performanceReach: [1200, 2400, 5100, 8900, 12200],
    },
    {
      id: "collab-2",
      campaignId: "campaign-bramble-design-week",
      campaignTitle: "Design Week spotlight",
      creatorProfileId: "creator-alexis",
      brandProfileId: "brand-bramble",
      brandName: "Bramble",
      brandLogoUrl: "/images/logos/bramble.svg",
      status: "needs_action",
      agreedPrice: 540,
      netPayoutToCreator: 405,
      nextActionText: "Review brief and confirm the post date",
      dueDate: "2026-09-14T00:00:00.000Z",
      performanceReach: [],
    },
    {
      id: "collab-3",
      campaignId: "campaign-northloop-forecast",
      campaignTitle: "Forecasting accuracy series",
      creatorProfileId: "creator-alexis",
      brandProfileId: "brand-northloop",
      brandName: "Northloop",
      brandLogoUrl: "/images/logos/northloop.svg",
      status: "applied",
      agreedPrice: 620,
      netPayoutToCreator: 465,
      nextActionText: "Waiting on brand review",
      dueDate: null,
      performanceReach: [],
    },
    {
      id: "collab-4",
      campaignId: null,
      campaignTitle: "Direct outreach — Series B intro post",
      creatorProfileId: "creator-alexis",
      brandProfileId: "brand-ferngrove",
      brandName: "Ferngrove",
      brandLogoUrl: "/images/logos/ferngrove.svg",
      status: "declined",
      agreedPrice: 400,
      netPayoutToCreator: 300,
      nextActionText: "Declined — timing conflict",
      dueDate: null,
      performanceReach: [],
    },
    {
      id: "collab-5",
      campaignId: "campaign-bramble-design-week",
      campaignTitle: "Onboarding walkthrough",
      creatorProfileId: "creator-alexis",
      brandProfileId: "brand-bramble",
      brandName: "Bramble",
      brandLogoUrl: "/images/logos/bramble.svg",
      status: "completed",
      agreedPrice: 480,
      netPayoutToCreator: 360,
      nextActionText: "Paid out",
      dueDate: "2026-07-30T00:00:00.000Z",
      performanceReach: [900, 3100, 6400, 9800, 11100, 11800],
    },
  ],
  marcus: [],
  juliette: [],
};
